export default function TermsOfService() {
  return (
    <section className="max-w-5xl mx-auto py-16 text-center px-4 md:px-0">
      <h1 className="text-3xl md:text-4xl font-bold font-montserrat">Terms of Service</h1>

      <div className="w-full space-y-8 text-left mt-12">
        <div>
          <h2 className="text-2xl font-bold font-montserrat">1. Acceptance of Terms</h2>
          <p className="text-slate-600 w-[80%]">
            By accessing or using PrettyAIColors, you agree to comply with these terms of service. If you do not agree with any part of these terms, please refrain from using the service.
          </p>
        </div>
        <div>
          <h2 className="text-2xl font-bold font-montserrat">2. Service Description</h2>
          <p className="text-slate-600 w-[80%]">PrettyAIColors is a free web application that allows users to generate, visualize, and save color palettes locally on their devices. The application uses artificial intelligence (AI) for color palette generation.</p>
        </div>
        <div>
          <h2 className="text-2xl font-bold font-montserrat">3. Use of Service</h2>
          <ul className="mt-2 text-slate-600 space-y-2">
            <li><span className="font-bold">Personal and Commercial Use</span>: You can use PrettyAIColors for personal and commercial purposes, such as generating color palettes for your website, application, or any other project.</li>
            <li><span className="font-bold">Responsible Use</span>: You are responsible for the use of the service and the data generated by it. You must not use the service for illegal or harmful purposes.</li>
            <li><span className="font-bold">No Malicious Use</span>: You must not use the service for any malicious or illegal purposes.</li>
          </ul>
        </div>
        <div>
          <h2 className="text-2xl font-bold font-montserrat">4. Intellectual Property</h2>
          <ul className="mt-2 text-slate-600 space-y-2">
            <li><span className="font-bold">User Content</span>: You are the owner of the content you generate using PrettyAIColors. You retain all rights to your generated content.</li>
            <li><span className="font-bold">AI ​​Content</span>: The AI ​​used in PrettyAIColors does not generate content that belongs to you. You do not have any rights to the AI ​​content generated by the service.</li>
            <li><span className="font-bold">Service Content</span>: The content of the service, including but not limited to the design, layout, and code, is owned by the developer. You may not use, modify, or distribute the service content without permission.</li>
          </ul>
        </div>
        <div>
          <h2 className="text-2xl font-bold font-montserrat">5. No Data Collection</h2>
          <p className="text-slate-600 w-[80%]">
          PrettyAIColors does not collect personal data from users. All information related to color palettes is stored locally on the user&apos;s device.
          </p>
        </div>
        <div>
          <h2 className="text-2xl font-bold font-montserrat">6. Donations</h2>
          <p className="text-slate-600 w-[80%]">
            Users donations are enterily voluntary and do not affect the functionality or access to PrettyAI Colors.
          </p>
        </div>
        <div>
          <h2 className="text-2xl font-bold font-montserrat">7. Liability</h2>
          <p className="text-slate-600 w-[80%]">
            PrettyAIColors is provided on an &quot;as is&quot; basis, without warranties of any kind, either express or implied. The developer will not be liable for any damages or injuries resulting from the use of the service.
          </p>
        </div>
        <div>
          <h2 className="text-2xl font-bold font-montserrat">8. Changes to Terms</h2>
          <p className="text-slate-600 w-[80%]">
            The developer reserves the right to modify these terms of service at any time. Changes will be effective immediately upon posting the updated terms.
          </p>
        </div>
      </div>
    </section>
  )
}